#! /usr/bin/env python
# encoding: utf-8


bld.program(
    features='cxx test',
    source=['relay_simulations.cpp'],
    target='relay_simulations',
    includes='..',
    use=['kodo_rlnc_includes', 'gauge'])
